PACKAGE = drcl.comp.lib

SOURCE  = \
		Bouncer.java \
		Delay.java \
		Relay.java \
		RNG.java \
		Stats.java \
		Talk.java \
		TextDisplay.java \
		SimpleReceiver.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
