PACKAGE = ..ptolemy.plot.plotml

SOURCE  = \
		PlotBoxMLParser.java \
		plotml.dtd \
		PlotMLFrame.java \
		PlotMLParser.java \
		PlotML_1.dtd \

RMI_SOURCE  = 

MAIN        = 

include $(JAVASIM)/Makefile
