PACKAGE = drcl.net.traffic

SOURCE  = \
		SimpleTrace.java \
		TCPTrace.java \
		TimestampedFooPacket.java \
		TraceInput.java \
		TrafficAssistant.java \
		TrafficComponent.java \
		TrafficModel.java \
		TrafficPeriodic.java \
		TrafficShaper.java \
		TrafficShaperComponent.java \
		TrafficSourceComponent.java \
		traffic_CDSmooth.java \
		traffic_ExpOnOff.java \
		traffic_FixedPoints.java \
		traffic_OnOff.java \
		traffic_PacketTrain.java \
		traffic_ParetoOnOff.java \
		traffic_PeakRate.java \
		traffic_Periodic.java \
		traffic_Poisson.java \
		traffic_PoissonVariableSize.java \
		traffic_RTSmooth.java \
		traffic_TokenBucket.java \
		tsCDSmooth.java \
		tsDummy.java \
		tsExpOnOff.java \
		tsFixedPoints.java \
		tsOnOff.java \
		tsPacketTrain.java \
		tsParetoOnOff.java \
		tsPeakRate.java \
		tsPeriodic.java \
		tsPoisson.java \
		tsPoissonVariableSize.java \
		tsRTSmooth.java \
		tsTokenBucket.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
