PACKAGE = ..ptolemy.gui

SOURCE  = \
		BasicJApplet.java \
		CancelException.java \
		CloseListener.java \
		ComponentDialog.java \
		GraphicalMessageHandler.java \
		MessageHandler.java \
		Query.java \
		QueryListener.java \
		StatusBar.java \
		Top.java \

RMI_SOURCE  = 

MAIN        = 

include $(JAVASIM)/Makefile
