PACKAGE = drcl.ruv

SOURCE  = \
		CommandOption.java \
		Commands.java \
		CommandTask.java \
		Common.java \
		Directory.java \
		drcl.tcl \
		Dterm.java \
		DtermAWT.java \
		DummyTerm.java \
		Paths.java \
		RUVOutput.java \
		RUVOutputManager.java \
		RUVPythonInterpreter.java \
		Shell.java \
		ShellContract.java \
		ShellEvalException.java \
		ShellFoo.java \
		ShellPython.java \
		ShellTcl.java \
		StackTraceFilter.java \
		System.java \
		SystemMonitor.java \
		TclAction.java \
		TclGateway.java \
		Term.java \
		TermExitListener.java \
		WaitUntil.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
