PACKAGE = drcl.comp.tool

SOURCE  = \
		ComponentDebugger.java \
		ComponentMonitor.java \
		ComponentTester.java \
		CountMonitor.java \
		CountMonitor2.java \
		DataCounter.java \
		DotDump.java \
		DotDump2.java \
		DrclPlotFrame.java \
		EventTester.java \
		HistogramPlotter.java \
		PlotPlain.java \
		Plotter.java \
		RunningAverage.java \
		TimerList.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
