PACKAGE = drcl.inet.protocol.dvmrp

SOURCE  = \
		DVMRP.java \
		DVMRPFCExtension.java \
		DVMRPFCPacket.java \
		DVMRPRTExtension.java \
		DVMRPRTPacket.java \
		DVMRPTimingPack.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
