PACKAGE = drcl.inet.protocol.cbt

SOURCE  = \
		CBT.java \
		CBTConstants.java \
		CBTInterface.java \
		CBTInterfaceTimer.java \
		CBTPacket.java \
		CBTState.java \
		CBTStateTimer.java \
		CBTTimer.java \
		CBTTimingPack.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
