PACKAGE = drcl.util.random

SOURCE  = \
		Constant.java \
		ExponentialDistribution.java \
		GaussianDistribution.java \
		LognormalDistribution.java \
		LognormalParetoDistribution.java \
		ParetoDistribution.java \
		RandomNumberGenerator.java \
		TruncatedLognormalDistribution.java \
		TruncatedParetoDistribution.java \
		UniformDistribution.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
