PACKAGE = drcl.inet.core.queue

SOURCE  = \
		DropTail.java \
		FIFO.java \
		FRED.java \
		MQueue.java \
		PreemptPriorityQueue.java \
		PriorityQueue.java \
		RED.java \
		SRED.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
