PACKAGE = drcl.inet.contract

SOURCE  = \
		ConfigSwitch.java \
		DatagramContract.java \
		IDConfig.java \
		IDLookup.java \
		IFQuery.java \
		McastHostEvent.java \
		NeighborEvent.java \
		PktDelivery.java \
		PktSending.java \
		RTConfig.java \
		RTLookup.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
