PACKAGE = drcl.intserv.scheduler

SOURCE  = \
		admission_DCTS.java \
		admission_GR.java \
		admission_PTSP.java \
		scheduler_Fifo.java \
		scheduler_PGPS.java \
		scheduler_SCFQ.java \
		scheduler_SFQ.java \
		scheduler_SP.java \
		scheduler_VC.java \
		scheduler_WF2Q.java \
		SpecR_DCTS.java \
		SpecR_Direct.java \
		SpecR_GR.java \
		SpecR_PTSP.java \
		SpecR_SP.java \
		Translator_DCTS.java \
		Translator_GR.java \
		Translator_PTSP_EA.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
