PACKAGE = drcl.comp

SOURCE  = \
		ACARuntime.java \
		ACATimer.java \
		ActiveComponent.java \
		AddComponentException.java \
		ARuntime.java \
		AWorkerThread.java \
		Component.java \
		ComponentBeanInfo.java \
		ComponentTemplate.java \
		ContextException.java \
		Contract.java \
		ContractAny.java \
		ContractMultiple.java \
		Extension.java \
		ForkChild.java \
		ForkEvent.java \
		ForkManager.java \
		ForkManagerLocal.java \
		ForkReceive.java \
		ForkSend.java \
		Handler.java \
		InfoPort.java \
		LockPack.java \
		Message.java \
		Port.java \
		PortBeanInfo.java \
		PortException.java \
		PortPack.java \
		RestartableComponent.java \
		SendReceiveException.java \
		SetIDException.java \
		Task.java \
		TaskFork.java \
		TaskNotify.java \
		TaskReceive.java \
		TaskSend.java \
		TaskSpecial.java \
		Util.java \
		Wire.java \
		WorkerThread.java \
		WorkerThreadException.java \
		WorkerThreadInterruptedException.java \
		Wrapper.java \
		WrapperComponent.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
