PACKAGE = ..ptolemy.plot

SOURCE  = \
		CmdLineArgException.java \
		copyright.txt \
		DatasetFormatter.java \
		EditablePlot.java \
		EditListener.java \
		EPSGraphics.java \
		Histogram.java \
		HistogramApplet.java \
		Plot.java \
		PlotApplet.java \
		PlotApplication.java \
		PlotBox.java \
		PlotDataException.java \
		PlotFormatter.java \
		PlotFrame.java \
		PlotLive.java \
		PlotLiveApplet.java \
		PlotPoint.java \

RMI_SOURCE  = 

MAIN        = 

include $(JAVASIM)/Makefile
