PACKAGE = drcl.util.queue

SOURCE  = \
		BSQueue.java \
		CalendarQueue.java \
		CalendarQueue2.java \
		CalendarQueue3.java \
		Element.java \
		FIFOQueue.java \
		FiniteFIFOQueue.java \
		FiniteQueue.java \
		FiniteQueueImpl.java \
		FiniteVSFIFOQueue.java \
		FiniteVSQueue.java \
		FiniteVSQueueImpl.java \
		FiniteVSSimpleQueue.java \
		Queue.java \
		QueueAssistant.java \
		QueueImpl.java \
		QueueOptionalImplException.java \
		SimpleQueue.java \
		SizedElement.java \
		Stack.java \
		TreeMapQueue.java \
		VariableSizeQueue.java \
		VariableSizeQueueImpl.java \
		VSBSQueue.java \
		VSFIFOQueue.java \
		VSSimpleQueue.java \
		VSStack.java \
		VSTreeMapQueue.java \
		_Element.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
