PACKAGE = drcl.inet.protocol.ospf

SOURCE  = \
		OSPF.java \
		OSPF_Area.java \
		OSPF_DBdesc.java \
		OSPF_Hello.java \
		OSPF_Interface.java \
		OSPF_LSA.java \
		OSPF_LSack.java \
		OSPF_LSA_Header.java \
		OSPF_LSrequest.java \
		OSPF_LSupdate.java \
		OSPF_LS_Database.java \
		OSPF_Neighbor.java \
		OSPF_Packet.java \
		OSPF_QoS.java \
		OSPF_RoutingEntry.java \
		OSPF_SPF_vertex.java \
		OSPF_TimeOut_EVT.java \
		rfc2676.txt \
		Router_LSA.java \
		Router_LSA_Link.java \
		Util.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
