PACKAGE = drcl.inet.socket

SOURCE  = \
		InetSocket.java \
		JSimSocketImpl.java \
		Launcher.java \
		NonblockingSocketHandler.java \
		SocketApplication.java \
		SocketConstants.java \
		SocketContract.java \
		SocketHandler.java \
		SocketMaster.java \
		SocketStates.java \
		TCP_full.java \
		TCP_socket.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
