PACKAGE = drcl.diffserv

SOURCE  = \
		Classifiers.java \
		DFConstants.java \
		DFProfile.java \
		DFUtil.java \
		HQS.java \
		Marker.java \
		Meter.java \
		TB_meter.java \
		TC_meter.java \
		TrafficConditioner.java \
		TSW_meter.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
