PACKAGE = drcl.comp.contract

SOURCE  = \
		ComponentMessage.java \
		DebugContract.java \
		DoubleEventContract.java \
		ErrorContract.java \
		EventContract.java \
		GarbageContract.java \
		PropertyContract.java \
		TraceContract.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
