PACKAGE = drcl.util.scalar

SOURCE  = \
		DoubleVector.java \
		IntInterval.java \
		IntSpace.java \
		IntUtil.java \
		IntVector.java \
		LongInterval.java \
		LongSpace.java \
		LongVector.java \
		Complex.java \
		WrapAroundException.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
