PACKAGE = drcl.intserv

SOURCE  = \
		Admission.java \
		IntServToS.java \
		NamTrace.java \
		QoSRequirement.java \
		RspecTranslator.java \
		Scheduler.java \
		SchedulerConfig.java \
		SpecAd.java \
		SpecFlow.java \
		SpecR.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
