PACKAGE = drcl.inet.transport

SOURCE  = \
		Connection.java \
		TCP.java \
		TCPb.java \
		TCPConstants.java \
		TCPPacket.java \
		TCPSink.java \
		UDP.java \
		UDPPacket.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
