PACKAGE = drcl.net

SOURCE  = \
		Address.java \
		FooPacket.java \
		Module.java \
		Packet.java \
		PacketException.java \
		PacketWrapper.java \
		PktClassifier.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
