PACKAGE = drcl.comp.lib.bytestream

SOURCE  = \
		ByteStreamConstants.java \
		ByteStreamContract.java \
		ByteStreamNetPeer.java \
		ByteStreamPeer.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
