PACKAGE = drcl.inet.tool

SOURCE  = \
		NamTrace.java \
		PktMonitor.java \
		routing_msp.java \
		routing_msp2.java \
		SGB_altToInet.java \
		LinkCost.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
