PACKAGE = drcl.inet.protocol.aodv

SOURCE  = \
		AODV.java \
		AODV_Packet.java \
		AODV_RERR.java \
		AODV_RREP.java \
		AODV_RREQ.java \
		AODV_RTEntry.java \
		AODV_TimeOut_EVT.java \
		UIUCInjector.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
