PACKAGE = ..com.microstar.xml

SOURCE  = \
		HandlerBase.java \
		README.txt \
		SAXDriver.java \
		XmlException.java \
		XmlHandler.java \
		XmlParser.java \

RMI_SOURCE  = 

MAIN        = 

include $(JAVASIM)/Makefile
