PACKAGE = drcl.net.tool

SOURCE  = \
		Classifier.java \
		NamTrace.java \
		Receiver.java \
		TG-Framework.txt \
		TrafficMonitor.java \
		TrafficMonitor2.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
