PACKAGE = drcl.inet.core

SOURCE  = \
		CoreServiceLayer.java \
		CoreServiceLayerBeanInfo.java \
		CSLBuilder.java \
		Hello.java \
		Hellov.java \
		Identity.java \
		InetCoreConstants.java \
		NI.java \
		PktDispatcher.java \
		PktFilter.java \
		PktFilterSwitch.java \
		Queue.java \
		QueueBeanInfo.java \
		QueueNI.java \
		RT.java \
		sIGMP.java \
		VIFPack.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
