PACKAGE = drcl.util

SOURCE  = \
		CircularBuffer.java \
		MemoryMonitor.java \
		MiscUtil.java \
		NumberUtil.java \
		ObjectUtil.java \
		StringUtil.java \
		TraceManager.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
