PACKAGE = drcl.inet.application

SOURCE  = \
		BulkSink.java \
		BulkSource.java \
		BulkSourceSink.java \
		FileSource.java \
		fsp.java \
		fspd.java \
		FSPMessage.java \
		ftp.java \
		ftpd.java \
		McastTestApp.java \
		SApplication.java \
		SUDPApplication.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
