PACKAGE = drcl.data

SOURCE  = \
		BitSet.java \
		BooleanObj.java \
		Countable.java \
		DoubleObj.java \
		IntObj.java \
		LongObj.java \
		Map.java \
		MapKey.java \
		NumberObj.java \
		RadixMap.java \
		Radixtree.doc \
		XYData.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
